### ISSUE TITLE
Better handling of help command

### ISSUE THREAD

**Issue by weitzman** [consolidation/annotated-command#134] opened 2017-11-26 13:18 UTC
### Steps to reproduce
`drush help` is a common mistake when user meant to type `drush list`. See https://drupal.stackexchange.com/questions/249793/how-to-list-all-the-commands-in-drush-9-aka-drush-help

### Expected behavior
Run `drush list`. If not possible, give better error message.

### Actual behavior
Error:
```
[Symfony\Component\Console\Exception\CommandNotFoundException]                                 
  Command  was not found. Pass --root or a @siteAlias in order to run Drupal-specific commands.  
```

### Debugging
I think things go awry at https://github.com/consolidation/annotated-command/blob/master/src/Options/AlterOptionsCommandEvent.php#L65. `$commandToDescribe` is null.

**Comment by greg-1-anderson** [comment] 2017-11-26 16:05
This does not happen in Robo:

<img width="571" alt="screen shot 2017-11-26 at 8 02 44 am" src="https://user-images.githubusercontent.com/612191/33241825-4c64915e-d280-11e7-8035-cf72da2beffe.png">

I think this is caused by the custom Drush help command.

**Comment by greg-1-anderson** [comment] 2017-11-26 16:06
Probably the Drush help command's first argument should be `$command_name`, like it is in Symfony.

**Comment by weitzman** [comment] 2017-11-27 14:21
First arg already is [$command_name](https://github.com/drush-ops/drush/blob/4f88ce5a4d09f60c0592091b9f70c9969af71e00/src/Commands/help/HelpCommands.php#L30). Any guidance is appreciated.

**Comment by greg-1-anderson** [comment] 2017-11-28 22:26
Fixed in https://github.com/drush-ops/drush/pull/3197

**Closed by greg-1-anderson** 2017-11-28 22:26 UTC
Labels: bug
